hostelmanager/urls.py
from django.conf.urls import url
from django.contrib import admin
from finder import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^genre/(?P<home_action>.*)/$', views.homeaction, name = "homeaction"),
    url(r'^directors/(?P<direc_action>.*)/$', views.direcaction, name = "direcaction"),
    url(r'^directors/$', views.directors, name = "directors"),
    url(r'^home/', views.home, name = "home"),
    url(r'^success/', views.success, name = "success"),
    url(r'^$',auth_views.login,{'template_name': 'finder/login.html'},name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^register/',views.index,name="index"),
    url(r'^about/',views.about,name="about"),
    url(r'^error/',views.error,name="error"),
    url(r'^search/', views.search, name = "search"),
    url(r'^movie/(?P<movie_prof>.*)/$' , views.movieprof , name = 'movieprof'),
    url(r'^movie/(?P<movie_prof>.*)/((?P<movie_rate>[0-9]+))$' , views.movierate , name = 'movierate'),
    url(r'^profile/(?P<cust_prof>.*)/$' , views.custprof , name = 'custprof'),

    #url(r'^details/$',views.details,name="details"),
]

finder/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Movie(models.Model):
	m_genre = models.CharField(max_length = 100, null = False, default = 'Action')
	m_title = models.CharField(max_length = 100 , default = None, null = False, primary_key = True)
	m_year = models.CharField(max_length = 200 , default = None, null = False)
	m_urating = models.FloatField(default = 10 , null = False)
	m_rrating = models.IntegerField(default = 100, null = False)
	m_uvote = models.IntegerField(default = 120)
	m_rvote = models.IntegerField(default = 20)
	m_dir = models.CharField(max_length = 200)
	m_url = models.CharField(max_length = 2000,default = None)
	m_description = models.CharField(max_length = 3000, default = "NICE")
	m_duration = models.CharField(default = None, null = False, max_length = 50)

	def __unicode__(self):
		return unicode(self.m_title)

class UserMovies(models.Model):
	c_name = models.CharField(null = False, max_length = 100, default = None)
	c_movie_title = models.CharField(null = False, max_length = 200, default = None)
	c_rating = models.FloatField(default = -1, null = False)
	c_time = models.IntegerField(default = 0, null = False)
	#def __unicode__(self):
	#	return unicode(self.u_movie_id)



class Customer(models.Model) :
	G_Choices = (
		('action','action') ,
		('animation','animation'),
		('crime' , 'crime'),
		('horror' , 'horror'),
		('sci-fi' , 'sci-fi'),
	)
	name = models.CharField(max_length=50,default=None,null=False, primary_key = True)
	reviewer = models.IntegerField(default = 0)
	Password = models.CharField(max_length=20,default=None,null=False)
	Genre1 = models.CharField(max_length = 20, default = 'Action' ,choices = G_Choices , null = False)
	Genre2 = models.CharField(max_length = 20, default = 'Romance' ,choices = G_Choices , null = False)
	Genre3 = models.CharField(max_length = 20, default = 'Thriller' ,choices = G_Choices , null = False)
	im_link = models.CharField(max_length = 1000, default = 'https://www.alaskapacific.edu/wp-content/uploads/2015/11/placeholder_profile_photo-200x200.png', null = False)
	def __unicode__(self):
		return unicode(self.name)

class Director(models.Model):
	d_name = models.CharField(max_length=100,default='Jane',primary_key = True,null = False)
	d_link = models.CharField(max_length=1000,default='https://www.alaskapacific.edu/wp-content/uploads/2015/11/placeholder_profile_photo-200x200.png')
	d_age = models.IntegerField(default = 40)
	d_bio = models.CharField(max_length=1000,default='Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.')
	def __unicode__(self):
		return unicode(self.d_name);

class Direcmovies(models.Model):
	direc_name = models.CharField(max_length= 100,null = False,default="Jane")
	direc_title = models.CharField(max_length = 100,null = False)

class watchtime(models.Model):
 	w_time = models.IntegerField(default = 1, null = False)

finder/forms.py
from django import forms
from models import Customer

class CustomerForm(forms.ModelForm) :
	class Meta:
		model = Customer
		fields = ['name','Password','Genre1','Genre2','Genre3']


			

finder/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import Http404
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from models import Customer,Movie, UserMovies, watchtime, Director, Direcmovies
from django.views.generic import View
from forms import CustomerForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import redirect
# from forms import CustomerForm

# Create your views here.

def login(request):
	all_customers = Customer.objects.all()
	return render(request,'login.html',{'all_customers' : all_customers})
def index(request) :
	form = CustomerForm(request.POST)
	if(request.method=='POST'):
		if(form.is_valid()):
			form.save()
			stu = Customer.objects.all()
			UserList = User.objects.all()
			for tm in stu:
				f = 0
				for che in UserList:
					if (tm.name == che.username):
						f = 1
						break
				if f==0:
					user = User.objects.create_user(username = tm.name,
													password = tm.Password,
													email = 'tm@gmail.com'
													)


			#print form.cleaned_data[Customer.name]
			#user = User.objects.create_user(username = {{form.name}}, 
			#								password = {{form.RollNo}},
			#								email = 'tm@gmail.com'
			#								)
			message = 'Successfully Registered'
			#return render(request,'success.html',{'message': message})
			return redirect("/success/", {'message' : message})

		else :
			form_error = "(Registration Failed. Username Exists!)"
			return render(request,'index.html',{'form': form,'form_error': form_error})
	else :
		form = CustomerForm(request.POST)
	return render(request,'index.html',{'form': form})



	
def search(request):
	tm = request.user.username
	alb = Customer.objects.all()
	all_movies1 = Movie.objects.all()
	query = request.GET.get("q")
	if query:
		all_movies1 = all_movies1.filter(m_title__icontains=query)
	paginator = Paginator(all_movies1,40)
	page = request.GET.get('page')
	try:
		all_movies = paginator.page(page)
	except PageNotAnInteger:
		all_movies = paginator.page(1)
	except EmptyPage:
		all_movies = paginator.page(paginator.num_pages)
	bad1 = 60
	bad2 = 40
	return render(request , 'search.html' , {'bad1' : bad1,'bad2' : bad2,'alb' : alb , 'all_movies' : all_movies , 'tm' : tm })
	
def home(request):
	tm = request.user.username
	alb = Customer.objects.all()
	all_movies1 = Movie.objects.all().order_by('-m_rrating')
	paginator = Paginator(all_movies1,40)
	page = request.GET.get('page')
	try:
		all_movies = paginator.page(page)
	except PageNotAnInteger:
		all_movies = paginator.page(1)
	except EmptyPage:
		all_movies = paginator.page(paginator.num_pages)
	bad1 = 60
	bad2 = 40
	return render(request , 'home.html' , {'bad1' : bad1,'bad2' : bad2,'alb' : alb , 'all_movies' : all_movies , 'tm' : tm })

def directors(request):
	tm = request.user.username
	all_directors1 = Director.objects.all()
	paginator = Paginator(all_directors1,20)
	page = request.GET.get('page')
	try:
		all_directors = paginator.page(page)
	except PageNotAnInteger:
		all_directors = paginator.page(1)
	except EmptyPage:
		all_directors = paginator.page(paginator.num_pages)
	return render(request , 'directorlist.html',{'all_directors' : all_directors , 'tm' : tm})


def homeaction(request,home_action):
	tm = request.user.username
	alb = Customer.objects.all()
	all_movies1 = Movie.objects.filter(m_genre = home_action)
	paginator = Paginator(all_movies1,10)
	page = request.GET.get('page')
	try:
		all_movies = paginator.page(page)
	except PageNotAnInteger:
		all_movies = paginator.page(1)
	except EmptyPage:
		all_movies = paginator.page(paginator.num_pages)
	bad1 = 60
	bad2 = 40
	return render(request , 'home.html' , {'bad1' : bad1,'bad2' : bad2,'alb' : alb , 'all_movies' : all_movies , 'tm' : tm })

def direcaction(request,direc_action):
	direc_movies = Direcmovies.objects.filter(direc_name = direc_action)
	tm = request.user.username
	for mv in direc_movies:
		print mv.direc_title
	director1 = get_object_or_404(Director, d_name = direc_action)
	return render(request , 'director.html' , {'tm' : tm, 'direc_movies' : direc_movies ,'director1' : director1})


def success(request):
	return render(request,'success.html')

def about(request):
	return render(request,'about.html')

def movieprof(request , movie_prof):
	tm = request.user.username
	cus = Customer.objects.all()
	fl = -1
	for var in cus:
		if(var.name == tm):
			tm1 = var
			fl = 1
			break

	if(fl == -1):
		return render(request,'error.html')

	revrate = request.GET.get('dpurl')
	if revrate:
		movieobj = Movie.objects.get(m_title = movie_prof)
		update1 = UserMovies.objects.filter(c_movie_title = movie_prof,c_name = tm1).count()
		gettime = watchtime.objects.get(pk = 1)
		time1 = gettime.w_time
		time1 = time1 + 1

		if(update1 == 0):
			userobj = UserMovies(c_name = tm1, c_movie_title = movie_prof, c_time = time1)
			userobj.save()

		test1 = UserMovies.objects.get(c_movie_title = movie_prof,c_name = tm1)
		print(test1.c_rating)
		if(int(test1.c_rating) == -1):
			print(movieobj.m_rrating*movieobj.m_rvote + int(revrate))
			revrating = (movieobj.m_rrating*movieobj.m_rvote + int(revrate))/(movieobj.m_rvote + 1)
			nvotes = movieobj.m_rvote + 1
			revrating = round(revrating,0)
			print(revrating)
			Movie.objects.filter(m_title = movie_prof).update(m_rrating = revrating)
			Movie.objects.filter(m_title = movie_prof).update(m_rvote = nvotes)
		else:
			revrating = (movieobj.m_rrating*movieobj.m_rvote + int(revrate) - test1.c_rating)/(movieobj.m_rvote)
			revrating = round(revrating,0)
			Movie.objects.filter(m_title = movie_prof).update(m_rrating = revrating)

		UserMovies.objects.filter(c_movie_title = movie_prof,c_name = tm1).update(c_time = time1)
		UserMovies.objects.filter(c_movie_title = movie_prof,c_name = tm1).update(c_rating = revrate)
		watchtime.objects.filter(pk = 1).update(w_time = time1) 
	
	mov = Movie.objects.all()
	fl = -1
	for var in mov:
		if (var.m_title == movie_prof):
			alb = var
			fl = 1
			break
	all_movies = UserMovies.objects.filter(c_name = tm)
	update1 = UserMovies.objects.filter(c_movie_title = movie_prof,c_name = tm).count()
	cate1 = -1
	if(update1 == 1):
		ate = UserMovies.objects.filter(c_movie_title = movie_prof,c_name = tm)
		for aa in ate:
			cate1 = aa.c_rating
	if (fl == -1):
		return render(request,'error.html')


	isreviewer = tm1.reviewer
	return render(request , 'movieprof.html' ,{'update1' : update1, 'isreviewer' : isreviewer
		,'alb' : alb , 'tm' : tm , 'all_movies' : all_movies, 'cate1' : cate1})

def error(request):
	return render(request,'error.html')

def custprof(request , cust_prof):
	dpurl = request.GET.get('dpurl')
	if dpurl:
		myobject = Customer.objects.filter(name=request.user.username).update(im_link=dpurl)

	tm = request.user.username
	cus = Customer.objects.all()
	fl = -1
	for var in cus:
		if(var.name == cust_prof):
			tm1 = var
			fl = 1
			break
	if(tm != cust_prof):
		fl = -2
	if (fl == -1):
		return render(request,'error.html')

	all_movies = Movie.objects.all()


	if (fl == -2):
		return render(request,'home.html',{'all_movies' : all_movies ,'tm' : tm})

	all_movies = UserMovies.objects.filter(c_name = tm).order_by('-c_time')[:26]
	print(all_movies.count())
	a = {}
	a1 = {}
	a2 = {}
	for mov in all_movies:
		curmov = Movie.objects.get(m_title = mov.c_movie_title)
		if curmov.m_dir in a:
			a[curmov.m_dir] = a[curmov.m_dir] + 1
		else:
			a[curmov.m_dir] = 1
		if curmov.m_genre in a1:
			a1[curmov.m_genre] = a1[curmov.m_genre] + 1
		else:
			a1[curmov.m_genre] = 1
		usrwatch = UserMovies.objects.filter(c_movie_title = mov.c_movie_title)
		for usr in usrwatch:
			if usr.c_name == tm1.name:
				break
			if usr.c_name in a2:
				a2[usr.c_name] = a2[usr.c_name] + 1
			else:
				a2[usr.c_name] = 1
	b = max(a,key = a.get)
	b1 = max(a1,key = a1.get)
	b2 = max(a2,key = a2.get)
	print(b)
	print(b1)
	print(b2)
	moviewatch = UserMovies.objects.filter(c_name = b2)
	pusermovies = UserMovies.objects.filter(c_name = tm)
	# ng_movie = null 
	# for mv in moviewatch:
	# 	f = 1
	# 	for pmv in pusermovies:
	# 		if pmv.c_name == mv.c_name:
	# 			f = 0
	# 			break
	# 	if f == 1:
	# 		mv = Movie.objects.get(m_title = mv.c_movie_title)
	# 		ng_movie = ng_movie + mv

	# movie7 = ng_movie.objects.raw('select * from finder_movie where m_title not in (select c_movie_title from finder_customer)')

	all_movies1 = Movie.objects.all()[:20]
	cust1 = tm1.Genre2
	movie1 = Movie.objects.raw('select * from finder_movie where m_genre = %s and m_title not in (select c_movie_title from finder_customer,finder_usermovies where c_name = name) order by m_urating desc',[tm1.Genre1])[:3]
	movie2 = Movie.objects.raw('select * from finder_movie where m_genre = %s and m_title not in (select c_movie_title from finder_customer,finder_usermovies where c_name = name) order by m_urating desc',[tm1.Genre2])[:3]
	movie3 = Movie.objects.raw('select * from finder_movie where m_genre = %s and m_title not in (select c_movie_title from finder_customer,finder_usermovies where c_name = name) order by m_urating desc',[tm1.Genre3])[:2]
	movie4 = Movie.objects.raw('select * from finder_movie where m_genre <> %s and m_genre != %s and m_genre != %s  and m_title not in (select c_movie_title from finder_customer,finder_usermovies where c_name = name) order by m_rrating desc',[tm1.Genre3,tm1.Genre2,tm1.Genre1])[:8]
	movie5 = Movie.objects.raw('select * from finder_movie where m_dir = %s and m_title not in (select c_movie_title from finder_customer,finder_usermovies where c_name = name) order by m_urating desc',[b])[:2]
	movie6 = Movie.objects.raw('select * from finder_movie where m_genre = %s and m_title not in (select c_movie_title from finder_customer,finder_usermovies where c_name = name) order by m_urating desc',[b1])[:2]

finder/templates/about.html
<html>
<head>
	<title>{% block title %}Movie Recommendation{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/test1.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/custom.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/booststrap-social.css' %}" />
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        

<style>
	
	.navli .nava {
		color: white !important;
	}
	.navli:hover .nava:hover {
		color: #707677 !important;
	}
	body {
  		padding-top: 0px;
	}
	@media(min-width: 992px) {
  		body{
   	 		padding-top: 0px;
  		}
	}
</style>

        
</head>


<body>


<nav class="navbar navbar-inverse"  style ="background-color: #CB2027;font-family:monospace;border-color: #CB2027">
    <div class="container-fluid">
	
	<ul class="nav navbar-nav navbar-right">
			<li class="navli">
				<a href="{% url 'home' %}" class="nava">	
					<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
					Home
				</a>
			</li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
			<li class="navli">
				<a href="{% url 'about' %}" class="nava">	
					<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp;
					About
				</a>
			</li>
	</ul>
</nav>

<h3 style ="text-align: center;color: #CB2027;font-family:monospace;">Our team</h3><!--Form-->

<!-- <p style ="text-align: center;color: #CB2027;font-family:monospace;">(Your status should be "Available" if you haven't got a roomie yet)</p> -->
<div class="row">
        <br>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p160x160/15400308_1112021352242317_3082742932907376064_n.jpg?_nc_cat=0&_nc_eui2=v1%3AAeHUTloc-y0h4Alh-otBVd-_fQolqK05pMRYQhZF404OJLE-Mn7P-MoSlSUM2lYzcnn-bLvPdWic5lTqO3cbROvpQcixjPQs1VyUx9gvl34ehA&oh=9a3b93eea5706eaaa46eb0d132718211&oe=5B6A659A" alt="">
          <h3>Ravi Chandra</h3>
          <a class="btn btn-block btn-social btn-lg btn-facebook" background-color = #3B5998 href="https://www.facebook.com/profile.php?id=100003033881330">
    			<span class="fa fa-facebook"></span>
    			Facebook
  		  </a>
  		  <a class="btn btn-block btn-social btn-lg btn-github" background-color = #3B5998 href="https://github.com/rc4594">
    			<span class="fa fa-github"></span>
    			Github
  		  </a>

          <p></p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p160x160/28795023_1650222338393312_4931548321907998720_n.jpg?_nc_cat=0&_nc_eui2=v1%3AAeEFZXAqGqe5XrlcWPpTiiig6xUV7HePbTW-Zqh_hYFzzfKnEmPgzisjr2pnHpPBnE6htt1MfanadWH0lQKD-lHc7jSHoJT30VMGYyUMu0yMQA&oh=f31b9e4feda031e6b9c18dab69b8f8d7&oe=5B6BD67F" alt="">
          <h3>Nitin Raj Singh</h3>
          <a class="btn btn-block btn-social btn-lg btn-facebook" background-color = #3B5998 href="https://www.facebook.com/Nitinrajsingh">
    			<span class="fa fa-facebook"></span>
    			Facebook
  		  </a>
  		  <a class="btn btn-block btn-social btn-lg btn-github" href="https://github.com/nitinrajsingh">
    			<span class="fa fa-github"></span>
    			Github
  		  </a>
          <p></p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="https://scontent-sit4-1.xx.fbcdn.net/v/t1.0-1/p160x160/20597398_728123947370901_6508535812400774135_n.jpg?_nc_cat=0&_nc_eui2=v1%3AAeHYvslD_Xzy9kz7qUUNU9Idwyv33deZ9PHqEiMfV04ssjOLUO_ZmjO0gS7TrbkJuOBRTZLnVWpuEaO0-irx_hGn-2Brxf3cLulk_d-7lWhJ4g&oh=c42819b8fd343881568d64cc9439a92a&oe=5B68BD7A" alt="">
          <h3>Sheldon Tauro</h3>
          <a class="btn btn-block btn-social btn-lg btn-facebook" background-color = #3B5998 href="https://www.facebook.com/sheldon.tauro.1">
    			<span class="fa fa-facebook"></span>
    			Facebook
  		  </a>
  		  <a class="btn btn-block btn-social btn-lg btn-github" background-color = #3B5998 href="https://github.com/sheldontauro">
    			<span class="fa fa-github"></span>
    			Github
  		  </a>
        </div>
      </div>

</div>
<br>
<br>

<br>



</body>
</html>

<!--  
<body>
 <h1>WElcome to the prject</h1>
   <form method="POST" action="" class="post-form">{% csrf_token %}
{{ form.as_p }}

        
{% for field in form %}
	{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
	<label>{{ field.label_tag }}</label>
	<div> {{ field }} </div>	
{% endfor %}

        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% if message %}
    <script>
    	alert('RegisteredSuccesfully')

    </script>
{% endif %}
</body> -->

finder/templates/director.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
	<!-- director1 , direc_movies -->

	<link rel="stylesheet"  href="{% static 'profile.css' %}">
	<div class="container profile">
		<div class="row">
			<div class = "col-md-4">
				  <img src="{{director1.d_link}}" style="display:block;margin:auto;" width=200px height=200>
				  <h1 class="text-center">{{director1.d_name}}</h1>
				  <!-- Button trigger modal -->
				  
            </div>
			<div class="col-md-8">
				<!-- <div class="container"> -->  
				<div class="row">
					<h3>BIO</h3>
					<p >{{director1.d_bio}}</p>
				</div>  
				<div class="row">
				  <h3>Known For</h3>
				  <table class="table table-striped">
				    <tbody>
				    	{% for mv in direc_movies %}
				    	 <tr>
				    	   <td><a href="{% url 'movieprof' mv.direc_title %}">{{mv.direc_title}}</a></td>
				    	 </tr>		
				    	{% endfor %}
				    </tbody>
				  </table>
				</div>
			</div>
		</div>
	</div>

<script>
	$("td").hover(function(){
    $(this).css("background-color", "transparent");
    }, function(){
    $(this).css("background-color", "transparent");
});
</script>
{% endblock %}

finder/templates/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
	
<div class="container">
	<div class="row">
	    <div class="col-md-12">
	        <h2 class="alert-danger">Sorry the page couldn't be displayed</h2> 
	    </div>
	</div>
<div class="row">
    <div class="col-md-12">
        <br>
        <img data-toggle='tooltip' title=':('  class="img-responsive center-block" src="{% static 'images/smile.png' %}" alt="Sorry!"/>
        <br>
    </div>
</div>
{% endblock %}

finder/templates/index.html
<html>
<head>
	<title>{% block title %}Movie Recommendation{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static '/style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/tables.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static '/custom.css' %}" />
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        

<style>
	.navli .nava {
		color: white !important;
	}
	.navli:hover .nava:hover {
		color: #707677 !important;
	}
</style>

        
</head>


<body>


<nav class="navbar navbar-inverse"  style ="background-color: #CB2027;font-family:monospace;border-color: #CB2027">
    <div class="container-fluid">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle">
		</button>
		<a class="navbar-brand" href="#" style="color:white">Registration Form</a>
	</div>
	<ul class="nav navbar-nav navbar-right">
			<li class="navli">
				<a href="{% url 'home' %}" class="nava">	
					<span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;
					Home
				</a>
			</li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
			<li class="navli">
				<a href="{% url 'about' %}" class="nava">	
					<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp;
					About
				</a>
			</li>
	</ul>
</nav>

<h3 style ="text-align: center;color: #CB2027;font-family:monospace;">Fill in you details here</h3><!--Form-->
<p style ="text-align: center;color: #CB2027;font-family:monospace;">(It is recommended to choose 3 different Genres)</p>
<div class="login-page">
  <div class="form">    
    <form class="login-form" method="POST" action="." role="form">
    	<p style ="text-align: center;color: #CB2027;font-family:monospace;">All Fields are compulsory</p>
    	{% csrf_token %}
     		<input id="id_name" type="text" placeholder="Name " name="name" required />
      		<input id="id_Password" type="Password" placeholder="Password." name="Password" required />
      
     
      		
			<p style="float:left;font-family:Monospace;color:#787A7A;">GENRE1:</p>
				<div style="font-family: Monospace">{{form.Genre1}}</div>
			<br>
			<p style="float:left;font-family:Monospace;color:#787A7A;">GENRE2:</p>
				<div style="font-family: Monospace">{{form.Genre2}}</div>
			<br>
			<p style="float:left;font-family:Monospace;color:#787A7A;">GENRE3:</p>
				<div style="font-family: Monospace">{{form.Genre3}}</div>
			<br><br>
      <div class="form-group"> 

      
      <button type='submit' class="center">Submit</button>
      
      
	</form>
	


  </div>
</div>
<br>
<br>



{% if message %}
<script>
    alert('RegisteredSuccesfully');
</script>
{% endif %}
{% if form_error %}
<script>
    alert('Username Exists');
</script>
{% endif %}

</body>
</html>

<!--  
<body>
 <h1>WElcome to the prject</h1>
   <form method="POST" action="" class="post-form">{% csrf_token %}
{{ form.as_p }}

        
{% for field in form %}
	{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
	<label>{{ field.label_tag }}</label>
	<div> {{ field }} </div>	
{% endfor %}

        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% if message %}
    <script>
    	alert('RegisteredSuccesfully')

    </script>
{% endif %}
</body> -->